image: xbane/repo:slc6-base

stages:
  - build
  - test

before_script:
    - export GCC_VERSION=4.8.1
    - export ROOT_VERSION=5.34.36
    - export DISPLAY=""
    - source .gitlab-ci.d/init_x86_64.sh

build:
  stage: build
  script:
    - cd test
    - ./build.sh
  artifacts:
    paths:
      - test/build/activate.sh
      - test/build/bin/

# global cache that should be shared among all jobs
cache:
  key: data
  paths:
    - test/raw/

test_configs:
  stage: test
  script:
    - cd test
    - ./check_configs.sh

test_run000875:
  stage: test
  script:
    - cd test
    - ./download_data.py
    - ./run_tel_noisescan.sh 875 -n 100000
    - ./run_tel_align.sh 875 -n 100000
    - ./run_track.sh 875 -n 100000
    - ./run_dut0_noisescan.sh 875 -n 100000

test_run001066:
  stage: test
  script:
    - cd test
    - ./download_data.py
    - ./run_tel_noisescan.sh 1066
    - ./run_tel_align.sh 1066
    - ./run_track.sh 1066
    - ./run_dut0_noisescan.sh 1066

test_old_run001066:
  stage: test
  script:
    - cd test
    - ./download_data.py
    - ./old-run_reference.sh 1066
