image: xbane/repo:slc6-base

stages:
  - build
  - test

before_script:
    - export GCC_VERSION=4.8.1
    - export ROOT_VERSION=5.34.36
    - export DISPLAY=""
    - source .gitlab-ci.d/init_x86_64.sh

build:
  stage: build
  script:
    - mkdir build
    - cd build
    # Build type=Debug: activates compilation of asserts and
    # includes debug symbols (See issue #43)
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build .
  artifacts:
    paths:
      - build/activate.sh
      - build/bin/

# global cache that should be shared among all jobs
cache:
  key: data
  paths:
    - test/raw/

check_configs:
  stage: test
  script:
    - source build/activate.sh
    - cd test
    - ./check_configs.sh

run000875_noisescan:
  stage: test
  script:
    - source build/activate.sh
    - cd test
    - ./download_data.py
    - ./run_tel_noisescan.sh 875 -n 100000 --no-progress
    - ./run_dut0_noisescan.sh 875 -n 100000 --no-progress

run000875_align:
  stage: test
  script:
    - source build/activate.sh
    - cd test
    - ./download_data.py
    - ./run_tel_align.sh 875 -n 100000 --no-progress

run000875_analysis:
  stage: test
  script:
    - source build/activate.sh
    - cd test
    - ./download_data.py
    - ./run_track.sh 875 -n 100000 --no-progress
    - ./run_match.sh 875 --no-progress

run001066_noisescan:
  stage: test
  script:
    - source build/activate.sh
    - cd test
    - ./download_data.py
    - ./run_tel_noisescan.sh 1066 --no-progress
    - ./run_dut0_noisescan.sh 1066 --no-progress

run001066_align:
  stage: test
  script:
    - source build/activate.sh
    - cd test
    - ./download_data.py
    - ./run_tel_align.sh 1066 --no-progress
    - ./run_dut_align.sh 1066 --no-progress

run001066_analysis:
  stage: test
  script:
    - source build/activate.sh
    - cd test
    - ./download_data.py
    - ./run_track.sh 1066 --no-progress
    - ./run_match.sh 1066 --no-progress
