image: gitlab-registry.cern.ch/ci-tools/ci-worker:slc6

stages:
  - build
  - test

# global cache that should be shared among all jobs
cache:
  key: data
  paths:
    - test/data/

# setup default build environment w/ minimal version requirements
# run debug build by default
before_script:
  - source /cvmfs/sft.cern.ch/lcg/views/LCG_92/x86_64-slc6-gcc62-opt/setup.sh
  - export "PATH=${PWD}/install-slc6-dbg/bin${PATH:+:}${PATH}"
  - export "LD_LIBRARY_PATH=${PWD}/install-slc6-dbg/lib${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH}"

check-format:
  # clang-format on ci yields different output from local installation
  allow_failure: true
  stage: build
  tags:
    - cvmfs
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . -- check-format

build-slc6-dbg:
  stage: build
  tags:
    - cvmfs
  variables:
    # Build type=Debug: activates compilation of asserts and
    # includes debug symbols (See issue #43)
    CMAKE_ARGS: -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install
  script:
    - mkdir build_external && cd build_external
    - cmake ${CMAKE_ARGS} ../ci/external
    # external tools are installed already during build step
    - cmake --build .
    - mkdir ../build && cd ../build
    - cmake ${CMAKE_ARGS} -DPROTEUS_USE_EUDAQ=on ..
    - cmake --build . -- install
  artifacts:
    paths:
      - install

build-slc6-opt:
  stage: build
  tags:
    - cvmfs
  variables:
    CMAKE_ARGS: -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${CI_PROJECT_DIR}/install-slc6-opt
  script:
    - mkdir build-external && cd build-external
    - cmake ${CMAKE_ARGS} ../ci/external
    # external tools are installed already during build step
    - cmake --build .
    - mkdir ../build && cd ../build
    - cmake ${CMAKE_ARGS} -DPROTEUS_USE_EUDAQ=on ..
    - cmake --build .

build-cc7-dbg:
  image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
  stage: build
  tags:
    - cvmfs
  before_script: []
  script:
    - source /cvmfs/sft.cern.ch/lcg/views/LCG_92/x86_64-centos7-gcc62-opt/setup.sh
    - mkdir build && cd build
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build .

build-cc7-opt:
  image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
  stage: build
  tags:
    - cvmfs
  before_script: []
  script:
    - source /cvmfs/sft.cern.ch/lcg/views/LCG_88/x86_64-centos7-gcc62-opt/setup.sh
    - mkdir build && cd build
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build .

doc:
  image: gitlab-registry.cern.ch/unige-fei4tel/proteus:cc7
  stage: build
  before_script: []
  script:
    - mkdir build && cd build
    - cmake -DPROTEUS_ENABLE_DOC=on ..
    - cmake --build . -- doc
  artifacts:
    paths:
      - build/doc/html

test-configs:
  stage: test
  tags:
    - cvmfs
  script:
    - source install/activate.sh
    - cd test
    - ./check_configs.sh

test-combine:
  stage: test
  tags:
    - cvmfs
  script:
    - source install/activate.sh
    - cd test
    - ./download_data.py unigetel_ebeam012_nparticles01 unigetel_ebeam120_nparticles02
    - ./check_combine.sh

# templates for dataset tests

.align_dut: &template_align_dut
  stage: test
  tags:
    - cvmfs
  script:
    - source install/activate.sh
    - cd test
    - ./download_data.py ${DATASET}
    - ./run_align_dut.sh ${DATASET} --no-progress

.align_tel: &template_align_tel
  stage: test
  tags:
    - cvmfs
  script:
    - source install/activate.sh
    - cd test
    - ./download_data.py ${DATASET}
    - ./run_align_tel.sh ${DATASET} --no-progress

.noisescan: &template_noisescan
  stage: test
  tags:
    - cvmfs
  script:
    - source install/activate.sh
    - cd test
    - ./download_data.py ${DATASET}
    - ./run_noisescan.sh ${DATASET} --no-progress

.recon: &template_recon
  stage: test
  tags:
    - cvmfs
  script:
    - source install/activate.sh
    - cd test
    - ./download_data.py ${DATASET}
    - ./run_recon.sh ${DATASET} --no-progress

# tests for UNIGEtel ebeam=12GeV nparticles=1

test-unigetel_ebeam012_nparticles01-align_dut:
  <<: *template_align_dut
  variables:
    DATASET: unigetel_ebeam012_nparticles01

test-unigetel_ebeam012_nparticles01-align_tel:
  <<: *template_align_tel
  variables:
    DATASET: unigetel_ebeam012_nparticles01

test-unigetel_ebeam012_nparticles01-noisescan:
  <<: *template_noisescan
  variables:
    DATASET: unigetel_ebeam012_nparticles01

test-unigetel_ebeam012_nparticles01-recon:
  <<: *template_recon
  variables:
    DATASET: unigetel_ebeam012_nparticles01

# tests for UNIGEtel ebeam=120GeV nparticles=1

test-unigetel_ebeam120_nparticles01-align_dut:
  <<: *template_align_dut
  variables:
    DATASET: unigetel_ebeam120_nparticles01

test-unigetel_ebeam120_nparticles01-align_tel:
  <<: *template_align_tel
  variables:
    DATASET: unigetel_ebeam120_nparticles01

test-unigetel_ebeam120_nparticles01-noisescan:
  <<: *template_noisescan
  variables:
    DATASET: unigetel_ebeam120_nparticles01

test-unigetel_ebeam120_nparticles01-recon:
  <<: *template_recon
  variables:
    DATASET: unigetel_ebeam120_nparticles01
