image: xbane/repo:slc6-base

stages:
  - build
  - data
  - test

before_script:
    - export GCC_VERSION=4.8.1
    - export ROOT_VERSION=5.34.36
    - export DISPLAY=""
    - source .gitlab-ci.d/init_x86_64.sh

cache:
  paths:
    - "test/raw"

build:
  stage: build
  script:
    - cd test
    - ./build.sh
  artifacts:
    paths:
      - "test/build/activate.sh"
      - "test/build/bin/proteus"
      - "test/build/bin/pt-analysis"
      - "test/build/bin/pt-cfg"
      - "test/build/bin/pt-noisescan"
      - "test/build/bin/pt-track"

download_data:
  stage: data
  script:
    - cd test
    - ./download_data.sh

test_run000875:
  stage: test
  script:
    - cd test
    - ./run_telescope.sh 875

test_run001066:
  stage: test
  script:
    - cd test
    - ./run_telescope.sh 1066

test_run001066_old:
  state: test
  script:
    - cd test
    - ./old-run_reference.sh 1066
