image: xbane/repo:slc6-base

stages:
  - build
  - test

# global cache that should be shared among all jobs
cache:
  key: data
  paths:
    - test/raw/

# setup default build environment w/ minimal version requirements
# run debug build by default
before_script:
  - source .gitlab-ci.d/cvmfs-slc6-gcc48-root534.sh
  - export "PATH=${PWD}/install-dbg/bin:${PATH}"

build-dbg:
  stage: build
  tags:
    - cvmfs
  script:
    - mkdir build-dbg
    - cd build-dbg
    # Build type=Debug: activates compilation of asserts and
    # includes debug symbols (See issue #43)
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install-dbg ..
    - cmake --build . -- install
  artifacts:
    paths:
      - install-dbg

build-rel:
  stage: build
  tags:
    - cvmfs
  script:
    - mkdir build-rel
    - cd build-rel
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install-rel ..
    - cmake --build . -- install
  artifacts:
    paths:
      - install-rel

build-gcc49-root606-rel:
  stage: build
  tags:
    - cvmfs
  before_script:
    - source .gitlab-ci.d/cvmfs-slc6-gcc49-root606.sh
  script:
    - mkdir build-gcc49-root606-rel
    - cd build-gcc49-root606-rel
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install-gcc49-root606-rel ..
    - cmake --build . -- install
  artifacts:
    paths:
      - install-gcc49-root606-rel

# TODO 2017-03-01 msmk: results in linker error w/ missing -lstdc++ library
#build-llvm39-root606-rel:
#  stage: build
#  before_script:
#    - source .gitlab-ci.d/cvmfs-slc6-llvm39-root606.sh
#  script:
#    - mkdir build-llvm39-root606-rel
#    - cd build-llvm39-root606-rel
#    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install-llvm39-root606-rel ..
#    - cmake --build . -- install
#  artifacts:
#    paths:
#      - install-llvm39-root606-rel

check_configs:
  stage: test
  tags:
    - cvmfs
  script:
    - cd test
    - ./check_configs.sh

run000875_noisescan:
  stage: test
  tags:
    - cvmfs
  script:
    - cd test
    - ./download_data.py
    - ./run_tel_noisescan.sh 875 -n 100000 --no-progress
    - ./run_dut0_noisescan.sh 875 -n 100000 --no-progress

run000875_align:
  stage: test
  tags:
    - cvmfs
  script:
    - cd test
    - ./download_data.py
    - ./run_tel_align.sh 875 -n 100000 --no-progress

run000875_analysis:
  stage: test
  tags:
    - cvmfs
  script:
    - cd test
    - ./download_data.py
    - ./run_track.sh 875 -n 100000 --no-progress
    - ./run_match.sh 875 --no-progress

run001066_noisescan:
  stage: test
  tags:
    - cvmfs
  script:
    - cd test
    - ./download_data.py
    - ./run_tel_noisescan.sh 1066 --no-progress
    - ./run_dut0_noisescan.sh 1066 --no-progress

run001066_align:
  stage: test
  tags:
    - cvmfs
  script:
    - cd test
    - ./download_data.py
    - ./run_tel_align.sh 1066 --no-progress
    - ./run_dut_align.sh 1066 --no-progress

run001066_analysis:
  stage: test
  tags:
    - cvmfs
  script:
    - cd test
    - ./download_data.py
    - ./run_track.sh 1066 --no-progress
    - ./run_match.sh 1066 --no-progress
