image: xbane/repo:slc6-base

stages:
  - build
  - run_reference
  - run_dut

cache:
  paths:
    - "test/raw"

before_script:
    - export GCC_VERSION=4.8.1
    - export ROOT_VERSION=5.34.36
    - export DISPLAY=""
    - source .gitlab-ci.d/init_x86_64.sh

build:
  stage: build
  script:
    - cd test
    - ./build.sh
  artifacts:
    paths:
      - "test/build/bin/proteus"
      - "test/build/activate.sh"

test_reference:
  stage: run_reference
  script:
    - cd test
    - ./download_data.sh
    - ./run_reference.sh
  artifacts:
    paths:
    #- "test/run000875"
    #- "test/run001066"

test_dut:
# DUT tests not ready, yet
  when: manual
  stage: run_dut
  script:
    - cd test
    - ./download_data.sh
    - ./run_dut.sh
  artifacts:
    paths:
      - "test/run000875"
      - "test/run001066"
      
